feat: Added logic to support metroLinks attribute for device linking request
equinix/terraform-provider-equinix pull request #621
Opened 2024-03-11 23:07 UTC by schadalawada

2024-04-02 00:22 UTC, rling-equinix requested changes

2024-04-02 00:22 UTC, rling-equinix commented on equinix/resource_network_device_link.go
> +			ValidateFunc: validation.StringInSlice([]string{"Primary", "Secondary", "Hybrid"}, true),
You can mark ignoreCase as false because all the available inputs will be shown in the terraform.

2024-04-02 00:22 UTC, rling-equinix commented on equinix/resource_network_device_link.go
> +		case networkDeviceLinkSchemaNames["RedundancyType"]:
We don't need to check the case here.

2024-04-02 00:22 UTC, rling-equinix commented on equinix/resource_network_device_link_test.go
> +				AccountNumber:      ne.String(""),
You can add some sample account numbers and reference ids here.

2024-04-02 00:22 UTC, rling-equinix commented on equinix/resource_network_device_link.go
> +	"golang.org/x/text/cases"
You can remove the case check dependencies here.

2024-04-02 00:23 UTC, rling-equinix commented
In general, the link to the API doc should be added in the description along with some contexts for the change.
The ne-go version should be bumped to pass the test cases.

2024-04-09 21:04 UTC, rling-equinix commented on docs/resources/equinix_network_device_link.md
> +* `redundancy_type` - (Optional) Whether the connection should be created through Fabric's primary or secondary port.Supported values: PRIMARY, SECONDARY, HYBRID
Default value should be added

2024-04-09 21:04 UTC, rling-equinix commented on equinix/resource_network_device_link.go
> +			Default:      "Primary",
Default value should be in upper case

2024-04-09 21:05 UTC, rling-equinix commented on equinix/resource_network_device_link.go
> +	if err := d.Set(networkDeviceLinkSchemaNames["RedundancyType"], strings.ToLower(*link.RedundancyType)); err != nil {
strings.ToLower() should be removed.

2024-04-09 21:08 UTC, rling-equinix commented on equinix/resource_network_device_link_test.go
> +		RedundancyType: ne.String("Primary"),
Primary should be in all upper case.

2024-04-09 21:12 UTC, rling-equinix commented on equinix/resource_network_device_link_test.go
> +		RedundancyType: ne.String("Primary"),
"Primary" should be in upper case

2024-04-09 21:20 UTC, rling-equinix approved these changes

2024-04-10 12:08 UTC, displague commented on equinix/resource_network_device_link.go
> +	"RedundancyType": "Device link redundancy type",
nit: the descriptions should be consistent with the markdown (https://github.com/equinix/terraform-provider-equinix/pull/621/files?diff=unified&w=1#diff-4c818a92bfcd55907ea7e51255ff4c04d63a494a1f0dd6e3b689388b11f1a350R53) to ease the path to #201

2024-04-10 12:13 UTC, displague commented on equinix/resource_network_device_link.go
> +			Description: networkDeviceLinkDescriptions["Links"],
`link` is deprecated in the markdown. I assume we want to actually deprecate the field here.
https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#provider-attribute-removal

2024-04-11 19:50 UTC, ctreatma approved these changes

2024-04-12 18:11 UTC, ctreatma approved these changes

2024-04-12 20:41 UTC, rling-equinix approved these changes

2024-04-12 21:01 UTC, merged