Feat: To Provide Support to create BlueCat devices through terraform
equinix/terraform-provider-equinix pull request #695
Opened 2024-06-10 17:46 UTC by kpdhulipala

Feat: To Provide Support to create BlueCat devices through terraform- BlueCat BDDS and BlueCat Edge Service Point

2024-06-10 18:43 UTC, rling-equinix requested changes

2024-06-10 18:43 UTC, rling-equinix commented on docs/resources/equinix_network_device.md
> +  vendor_configuration = {"hostname"="test","privateAddress":"x.x.x.x","privateCidrMask":"24", "privateGateway": "x.x.x.x", "licenseKey":"xxxxx-xxxxx-xxxxx-xxxxx-xxxxx", "licenseId":"xxxxxxxxxxxxxxx"
Could you split the attributes into multiple lines to make it easier to read?

2024-06-10 18:43 UTC, rling-equinix commented on docs/resources/equinix_network_device.md
> +    vendor_configuration = {"hostname"="test","privateAddress":"x.x.x.x","privateCidrMask":"24", "privateGateway": "x.x.x.x", "licenseKey":"xxxxx-xxxxx-xxxxx-xxxxx-xxxxx", "licenseId":"xxxxxxxxxxxxxx
Same here.

2024-06-10 18:43 UTC, rling-equinix commented on equinix/resource_network_device.go
> +	"PrivateAddress":    "private address. This field is relevant only for the BlueCat DNS and DHCP Server",
The sentence should start with upper case.

2024-06-10 18:43 UTC, rling-equinix commented on equinix/resource_network_device.go
> +			Optional:    true,
Could you add forceNew if change of the attribute will trigger device recreation?

2024-06-10 18:43 UTC, rling-equinix commented on equinix/resource_network_device.go
> +			Optional:    true,
If it is sensitive, the flag for sensitive should also be marked as true.

2024-06-10 23:46 UTC, rling-equinix approved these changes

2024-06-10 23:49 UTC, schadalawada approved these changes

2024-06-11 14:17 UTC, ctreatma approved these changes
Looks like the `CODEOWNERS` mapping is not correct; I think GitHub is forcing DRE review due to the docs change.  Approving to satisfy GitHub, and we'll work on fixing ownership in a separate PR.

2024-06-11 16:57 UTC, merged